/* DO NOT EDIT THIS FILE - it is machine generated */
// #include <jni.h>
/* Header for class AccessBridgeTester */

#ifndef _Included_AccessBridgeTester
#define _Included_AccessBridgeTester
#ifdef __cplusplus
extern "C" {
#endif
#undef AccessBridgeTester_ACCESS_BRIDGE_COMPATIBILITY
#define AccessBridgeTester_ACCESS_BRIDGE_COMPATIBILITY 2L
#undef AccessBridgeTester_AWT_EVENT_LISTENER_COMPATIBILITY
#define AccessBridgeTester_AWT_EVENT_LISTENER_COMPATIBILITY 4L
#undef AccessBridgeTester_HAS_1_3_APIS
#define AccessBridgeTester_HAS_1_3_APIS 8L
#ifdef __cplusplus
}
#endif
#endif
